language: node_js
node_js:
- '16.5'
install:
- npm install -g markdownlint-cli
- npm install -g @stoplight/spectral
jobs:
  include:
    - stage: List pending TODOs
      script:
        - egrep -R -i TODO *
    - stage: Markdown documentation lint
      script:
        - markdownlint './docs/**/*.md'
    - stage: OpenAPI 3 specifications lint
      script:
        - spectral lint ./reference/*.yaml --verbose
