language: node_js
node_js:
- '16.5'
install:
- npm install -g markdownlint-cli
- npm install -g @stoplight/spectral
script:
- echo "******* Pending TODOs *******"
- egrep -R -i TODO *
- echo "******* Markdown lint *******"
- markdownlint './docs/**/*.md'
- echo "******* OpenAPI 3 lint *******"
- spectral lint ./reference/*.yaml --verbose
