language: node_js
node_js:
- '16.5'
jobs:
  include:
    - stage: List pending TODOs
      script:
        - egrep -R -i TODO *
    - stage: Lint the Markdown documentation
      install:
        - npm install -g markdownlint-cli
      script:
        - markdownlint './docs/**/*.md'
    - stage: Lint the OpenAPI 3 specifications
      install:
        - npm install -g @stoplight/spectral
      script:
        - spectral lint ./reference/*.yaml --verbose
