git:
  depth: 3
language: node_js
node_js:
  - 16
jobs:
  include:
    - stage: List pending TODOs
      script:
        - egrep -R -i TODO *
    - stage: Validate
      install:
        - npm install -g markdownlint-cli
        - markdownlint --version
      script:
        - rake validate:docs:all
    - install:
        - npm install -g @apidevtools/swagger-cli
        - npm install -g @stoplight/spectral
        - npm install -g @openapitools/openapi-generator-cli
        - swagger-cli --version
        - spectral --version
        - openapi-generator --version
      script:
        - rake validate:specs:all
    - stage: Generate
      install:
        - npm install -g @apidevtools/swagger-cli
        - npm install -g @openapitools/openapi-generator-cli
        - swagger-cli --version
        - openapi-generator --version
      script:
        - rake generate:docs:all
    - install:
        - npm install -g @apidevtools/swagger-cli
        - npm install -g @openapitools/openapi-generator-cli
        - swagger-cli --version
        - openapi-generator --version
      script:
        - rake generate:client:all
    - install:
        - npm install -g @apidevtools/swagger-cli
        - npm install -g @openapitools/openapi-generator-cli
        - swagger-cli --version
        - openapi-generator --version
      script:
        - rake generate:server:all
    - install:
        - npm install -g @apidevtools/swagger-cli
        - npm install -g openapi-to-postmanv2
        - swagger-cli --version
        - openapi-generator --version
      script:
        - rake generate:server:all
