openapi: 3.0.0
info:
  title: clinic
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /clinics:
    get:
      summary: GetClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./clinic/models/Clinic.v1.yaml
      operationId: get-clinics
      description: Retrieve list of clinics.  Requires admin app authorization
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: ''
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
      requestBody:
        description: ''
    parameters: []
  /clinic:
    post:
      summary: CreateClinic
      tags: []
      responses:
        '200':
          description: OK
      operationId: post-clinic
      description: Creates a Clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/NewClinic.v1.yaml
  '/clinic/{clinicid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./clinic/models/Clinic.v1.yaml
      operationId: get-clinic-clinicid
    patch:
      summary: ModifyClinic
      operationId: patch-clinic-clinicid
      responses:
        '200':
          description: OK
      description: Modify Clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/NewClinic.v1.yaml
          application/xml:
            schema:
              type: object
              properties: {}
        description: Modify Clinic object
    delete:
      summary: DeleteClinic
      operationId: delete-clinic-clinicid
      responses:
        '200':
          description: OK
      description: Delete Clinic
  '/clinics/{clinicid}/clinicians':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetCliniciansForClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./clinic/models/Clinician.v1.yaml
      operationId: get-clinics-clinicid-clinicians
      description: Retrieve a list of clinicians for a clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
  '/clinic/{clinicid}/clinician/{clinicianid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: clinicianid
        in: path
        required: true
    delete:
      summary: DeleteClinicianForClinic
      tags: []
      responses:
        '200':
          description: OK
      operationId: delete-clinic-clinicid-clinician-clinicianid
      description: Remove association with clinic and clinician
    post:
      summary: AddClinicianToClinic
      operationId: post-clinic-clinicid-clinician-clinicianid
      responses:
        '200':
          description: OK
      description: Add a Clinician to a Clinic
  '/clinic/{clinicid}/patients':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetCliniciansForClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./clinic/models/Patient.v1.yaml
      operationId: get-clinic-clinicid-patients
      description: Get list of patients associated with clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
  '/clinic/{clinicid}/patient/{patientid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: patientid
        in: path
        required: true
    delete:
      summary: DeletePatientFromClinic
      tags: []
      operationId: delete-clinic-clinicid-patient-patientid
      description: delete patient from clinic
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      summary: AddPatientToClinic
      operationId: post-clinic-clinicid-patient-patientid
      responses:
        '200':
          description: OK
      description: Add patient to clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/PatientClinicRelationship.v1.yaml
components:
  schemas: {}
