openapi: 3.0.0
info:
  title: clinic
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /clinics:
    get:
      summary: GetClinics
      x-roles: ["TIDEPOOL_ADMIN"]
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./clinic/models/Clinic.v1.yaml
      operationId: get-clinics
      description: Retrieve list of clinics.  Requires admin app authorization
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: ''
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
    parameters: []
    post:
      summary: AddClinic
      x-roles: ["TIDEPOOL_ADMIN"]
      tags: []
      operationId: post-clinics
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/NewClinic.v1.yaml
      description: Add a new clinic
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
  '/clinics/{clinicid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN", "CLINIC_CLINICIAN"]
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./clinic/models/Clinic.v1.yaml
      operationId: get-clinics-clinicid
      description: Get Clinic
      security:
        - ClinicAuth:
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
            - TIDEPOOL_ADMIN
    patch:
      summary: ModifyClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN"]
      tags: []
      operationId: patch-clinics-clinicid
      responses:
        '200':
          description: OK
      description: Modify Clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/NewClinic.v1.yaml
          application/xml:
            schema:
              type: object
              properties: {}
        description: Modify Clinic object
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
    delete:
      summary: DeleteClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN"]
      tags: []
      operationId: delete-clinics-clinicid
      responses:
        '200':
          description: OK
      description: Delete Clinic
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
  '/clinics/{clinicid}/clinicians/{clinicianid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: clinicianid
        in: path
        required: true
    delete:
      summary: DeleteClinicianFromClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN"]
      tags: []
      responses:
        '200':
          description: OK
      operationId: delete-clinics-clinicid-clinicians-clinicianid
      description: Remove association with clinic and clinician
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
    patch:
      summary: ModifyClinicClinician
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN"]
      tags: []
      operationId: patch-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/ClinicianPermissions.v1.yaml
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
    get:
      summary: GetClinician
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN", "CLINIC_CLINICIAN"]
      tags: []
      operationId: get-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./clinic/models/ClinicsClinicians.v1.yaml
      description: Get a clinician object
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
  '/clinics/{clinicid}/patients':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetPatientsForClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN", "CLINIC_CLINICIAN"]
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./clinic/models/ClinicsPatients.v1.yaml
      operationId: get-clinics-clinicid-patients
      description: Get list of patients associated with clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
    post:
      summary: AddPatientToClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN", "CLINIC_CLINICIAN"]
      tags: []
      operationId: post-clinics-clinicid-patients
      responses:
        '200':
          description: OK
      description: Add patient to clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/ClinicsPatients.v1.yaml
        description: ''
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
  '/clinics/{clinicid}/patients/{patientid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: patientid
        in: path
        required: true
    delete:
      summary: DeletePatientFromClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN", "CLINIC_CLINICIAN"]
      tags: []
      operationId: delete-clinic-clinicid-patients-patientid
      description: delete patient from clinic
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
    get:
      summary: GetPatientFromClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN", "CLINIC_CLINICIAN"]
      tags: []
      operationId: get-clinics-clinicid-patients-patientid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./clinic/models/ClinicsPatients.v1.yaml
      description: Get a patient from clinic
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
    patch:
      summary: ModifyClinicPatient
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN", "CLINIC_CLINICIAN"]
      tags: []
      operationId: patch-clinics-clinicid-patients-patientid
      responses:
        '200':
          description: OK
      description: Modify a patient from clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/PatientPermissions.v1.yaml
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
  '/clinics/{clinicid}/clinicians':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetCliniciansFromClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN", "CLINIC_CLINICIAN"]
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./clinic/models/ClinicsClinicians.v1.yaml
      operationId: get-clinics-clinicid-clinicians
      description: Retrieve a list of clinicians for a clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
            - CLINIC_CLINICIAN
    post:
      summary: AddClinicianToClinic
      x-roles: ["TIDEPOOL_ADMIN", "CLINIC_ADMIN"]
      tags: []
      operationId: post-clinics-clinicid-clinicians
      responses:
        '200':
          description: OK
      description: Add a clinician to clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/ClinicsClinicians.v1.yaml
      security:
        - ClinicAuth:
            - TIDEPOOL_ADMIN
            - CLINIC_ADMIN
components:
  schemas: {}
  securitySchemes:
    ClinicAuth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://www.tidepool.org/auth'
          scopes:
            TIDEPOOL_ADMIN: Tidepool Administrator
            CLINIC_ADMIN: Clinic Administrator
            CLINIC_CLINICIAN: Clinician at Clinic
            CLINIC_PATIENT: Patient of Clinic
            CLINIC_PRESCRIBER: Clinician at Clinic with Prescriber Role
          refreshUrl: 'https://www.tidepool.org/refresh'
