openapi: 3.0.0
info:
  title: clinic
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /clinics:
    get:
      summary: GetClinics
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./clinic/models/Clinic.v1.yaml
      operationId: get-clinics
      description: Retrieve list of clinics.  Requires admin app authorization
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: ''
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
    parameters: []
    post:
      summary: AddClinic
      operationId: post-clinics
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/NewClinic.v1.yaml
      description: Add a new clinic
  '/clinics/{clinicid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./clinic/models/Clinic.v1.yaml
      operationId: get-clinics-clinicid
      description: Get Clinic
    patch:
      summary: ModifyClinic
      operationId: patch-clinics-clinicid
      responses:
        '200':
          description: OK
      description: Modify Clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/NewClinic.v1.yaml
          application/xml:
            schema:
              type: object
              properties: {}
        description: Modify Clinic object
    delete:
      summary: DeleteClinic
      operationId: delete-clinics-clinicid
      responses:
        '200':
          description: OK
      description: Delete Clinic
  '/clinics/{clinicid}/clinicians/{clinicianid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: clinicianid
        in: path
        required: true
    delete:
      summary: DeleteClinicianFromClinic
      tags: []
      responses:
        '200':
          description: OK
      operationId: delete-clinics-clinicid-clinicians-clinicianid
      description: Remove association with clinic and clinician
    patch:
      summary: ModifyClinicClinician
      operationId: patch-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/ClinicianPermissions.v1.yaml
    get:
      summary: GetClinician
      operationId: get-clinics-clinicid-clinicians-clinicianid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./clinic/models/ClinicsClinicians.v1.yaml
      description: Get a clinician object
  '/clinics/{clinicid}/patients':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetPatientsForClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./clinic/models/ClinicsPatients.v1.yaml
      operationId: get-clinics-clinicid-patients
      description: Get list of patients associated with clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
    post:
      summary: AddPatientToClinic
      operationId: post-clinics-clinicid-patients
      responses:
        '200':
          description: OK
      description: Add patient to clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/ClinicsPatients.v1.yaml
  '/clinics/{clinicid}/patients/{patientid}':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
      - schema:
          type: string
        name: patientid
        in: path
        required: true
    delete:
      summary: DeletePatientFromClinic
      tags: []
      operationId: delete-clinic-clinicid-patient-patientid
      description: delete patient from clinic
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    get:
      summary: GetPatientFromClinic
      operationId: get-clinics-clinicid-patient-patientid
      responses:
        '200':
          description: OK
      description: Get a patient from clinic
    patch:
      summary: ModifyClinicPatient
      operationId: patch-clinics-clinicid-patients-patientid
      responses:
        '200':
          description: OK
      description: Modify a patient from clinic
  '/clinics/{clinicid}/clinicians':
    parameters:
      - schema:
          type: string
        name: clinicid
        in: path
        required: true
    get:
      summary: GetCliniciansFromClinic
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./clinic/models/ClinicsClinicians.v1.yaml
      operationId: get-clinics-clinicid-clinicians
      description: Retrieve a list of clinicians for a clinic
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: sortOrder
    post:
      summary: AddClinicianToClinic
      operationId: post-clinics-clinicid-clinicians
      responses:
        '200':
          description: OK
      description: Add a clinician to clinic
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./clinic/models/ClinicsClinicians.v1.yaml
components:
  schemas: {}
