openapi: 3.0.0
info:
  title: Export API
  version: '1.0'
  description: |-
    ![Tidepool Logo](../assets/images/Tidepool_Logo_Light_Large.png)

    The Tidepool API is an HTTP REST API used by Tidepool clients use to communicate with the Tidepool Platform.

    For more information, see the [Getting Started](../docs/quick-start.md) section.
  termsOfService: https://developer.tidepool.org/terms-of-use/
  contact:
    name: Tidepool Api Support
    url: https://support.tidepool.org
    email: support@tidepool.org
  license:
    name: BSD-2-Clause
    url: https://github.com/tidepool-org/export/blob/master/LICENSE
  x-tidepool-service: https://github.com/tidepool-org/export

servers:
  - url: 'http://localhost:8080'
    description: local development
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production

tags:
  - name: Export
    description: >-
      Enable bulk export of diabetes data from user's Tidepool account.

paths:
  /export/status:
    get:
      responses:
        '200':
          description: 'Service status'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportServiceStatus'
      summary: Get service status
      description: Get export service status
      operationId: ExportServiceStatus
      x-private: true
      tags:
        - Export

  '/export/{userId}':
    parameters:
      - $ref: './common/parameters/tidepooluserid.v1.yaml'
    get:
      summary: Export user data
      description: >-
        Exports the diabetes data from user identified by `userId`, from `startDate` to `endDate`, in the requested `format`.
        Either a Tidepool session token, or a restricted token must be supplied.
      parameters:
        - name: startDate
          in: query
          schema:
            $ref: './common/models/datetime.v1.yaml'
        - name: endDate
          in: query
          schema:
            $ref: './common/models/datetime.v1.yaml'
        - name: format
          description: Export format
          in: query
          schema:
            type: string
            enum:
              - json
              - xlsx
            default: xlsx
        - name: bgUnits
          in: query
          schema:
            type: string
            enum:
              - mmol/L
              - mg/dL
            default: mmol/L
      responses:
        '200':
          description: >-
            User data exported in the requested `format`.
          headers:
            Content-Disposition:
              description: >-
                Tells the browser to show a `Save As` dialog box to save the exported file locally.
              schema:
                type: string
                default: 'attachment; filename="TidepoolExport.{format}"'
          content:
            application/json:
              $ref: '#/components/schemas/ExportAsJson'
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              $ref: '#/components/schemas/ExportAsExcel'
        # '400':
        #   $ref: './common/responses/badrequest.v1.yaml'
        # '401':
        #   $ref: './common/responses/unauthorized.v1.yaml'
        # '403':
        #   $ref: './common/responses/forbidden.v1.yaml'
      security:
        - sessionToken: []
        - restrictedToken: []
      operationId: ExportUserData
      x-private: true
      tags:
        - Export

components:
  securitySchemes:
    sessionToken:
      type: apiKey
      name: X-Tidepool-Session-Token
      in: header

    restrictedToken:
      type: apiKey
      name: restricted_token
      in: query

  schemas:
    ExportServiceStatus:
      type: object
      properties:
        status:
          type: string
          example: ok
          default: ok

    ExportAsJson:
      schema:
        $ref: './data/models/dataarray.v1.yaml'

    ExportAsExcel:
      schema:
        type: string
        format: binary
        description: An Excel spreadsheet
