swagger: '2.0'
info:
  title: Export Service API
  version: '1.0'
  termsOfService: 'https://developer.tidepool.org/terms-of-use/'
  license:
    name: BSD-2-Clause
  contact:
    name: Tidepool Api Support
    url: 'https://support.tidepool.org'
    email: support@tidepool.org
host: int-api.tidepool.org
paths:
  /export/status:
    get:
      responses:
        '200':
          description: ''
          schema:
            allOf:
              - $ref: '#/definitions/status'
          examples:
            application/json:
              uptime: 532641.68
      summary: Get service status
      operationId: Status
      x-private: true
  '/export/{userId}':
    get:
      responses:
        '200':
          description: ''
          schema:
            oneOf:
              - $ref: './data.oas2.yml#/definitions/DataArray'
              - type: string
                format: binary
                description: An Excel spreadsheet
        '401':
          description: ''
      summary: Get export for user
      produces:
        - application/json
        - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      parameters:
        - $ref: './common.oas2.yml#/parameters/tp-userid-param'
        - in: query
          name: startDate
          type: string
          format: date-time
        - in: query
          name: endDate
          type: string
          format: date-time
        - in: query
          name: format
          type: string
          enum:
            - json
            - xlsx
          default: xlsx
        - in: query
          name: bgUnits
          type: string
          default: mmol/L
          enum:
            - mmol/L
            - mg/dL
      security:
        - tidepool-session-token: []
        - tidepool-restricted-token: []
      operationId: ExportUser
      x-private: true
    parameters:
      - $ref: './common.oas2.yml#/parameters/tp-userid-param'
securityDefinitions:
  tidepool-session-token:
    type: apiKey
    name: x-tidepool-session-token
    in: header
  tidepool-restricted-token:
    type: apiKey
    name: restricted_token
    in: query
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
definitions:
  status:
    type: object
    properties:
      uptime:
        type: number
        minimum: 0
