openapi: 3.0.0
info:
  title: Tidepool API
  version: '1.0'
  description: Client library for interacting with the Tidepool APIs. For more information
    on the Tidepool APIs, see the Tidepool Developer Docs or the Tidepool SDK
    user guide.
  termsOfService: https://developer.tidepool.org/terms-of-use/
  contact:
    name: API Support
    url: https://support.tidepool.org
    email: support@tidepool.org
  license:
    name: BSD-2-Clause
    url: https://opensource.org/licenses/BSD-2-Clause
paths: {}
servers:
  - url: 'http://localhost:8080'
    description: local development
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production
