swagger: '2.0'
info:
  title: Tidepool API
  version: '1.0'
  description: >-
    Client library for interacting with the Tidepool APIs. For more information
    on the Tidepool APIs, see the Tidepool Developer Docs or the Tidepool SDK
    user guide.
  termsOfService: 'https://developer.tidepool.org/terms-of-use/'
  contact:
    name: API Support
    url: 'https://support.tidepool.org'
    email: support@tidepool.org
  license:
    name: BSD-2-Clause
    url: 'https://opensource.org/licenses/BSD-2-Clause'
host: int-api.tidepool.org
paths: {}
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
