openapi: 3.0.0
info:
  title: Metadata API
  version: '1.0'
paths:
  '/metadata/users/{userId}/users':
    get:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
      summary: List Users
      tags:
        - metadata
      security:
        - sessionToken: []
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
  '/metadata/{userId}/profile':
    put:
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
      summary: Update Account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      security:
        - sessionToken: []
      operationId: UpdateAccount
      tags:
        - metadata
    parameters:
      - $ref: ./common.oas2.yml#/components/parameters/tp-userid-param
tags:
  - name: metadata
servers:
  - url: https://int-api.tidepool.org
components:
  securitySchemes:
    sessionToken:
      type: apiKey
      name: x-tidepool-session-token
      in: header