openapi: 3.0.0
info:
  title: Summary Data
  version: '1.0'
  description: |-
    The Tidepool API is an HTTP REST API used by Tidepool clients use to communicate with the Tidepool Platform.

    For more information, see the [Getting Started](../docs/quick-start.md) section.
  contact:
    name: API Support
    url: 'https://support.tidepool.org/'
    email: support@tidepool.org
  termsOfService: 'https://developer.tidepool.org/terms-of-use/'
  license:
    name: 'BSD 2-Clause "Simplified" License'
    url: 'https://github.com/tidepool-org/summary/blob/master/LICENSE'
  x-tidepool-service: https://github.com/tidepool-org/summary

servers:
  - url: 'http://localhost:8080'
    description: local development
  - url: 'https://dev1.dev.tidepool.org'
    description: dev1
  - url: 'https://qa1.development.tidepool.org'
    description: qa1
  - url: 'https://qa2.development.tidepool.org'
    description: qa2
  - url: 'https://external.integration.tidepool.org'
    description: integration
  - url: 'https://api.tidepool.org'
    description: production

security:
  - sessionToken: []

tags:
  - name: Internal
    description: >-
      APIs intended for internal use by Tidepool.
  - name: Summary
    description: |-
      Summary Data

      This service was a prototype for separate service that calculates summary statistics for user accounts.
      It is replaced by additional APIs exposed by the `data` service, and executed by the `task` service.
      This documentation is for archival only.

paths:
  '/v1/users/{userId}/summary':
    parameters:
      - $ref: './common/parameters/tidepooluserid.yaml'
    post:
      operationId: GetUserSummary
      summary: Get User Summary
      description: >-
        Retrieves summary information for the user specified by `userId`.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './summary/models/summaryrequest.v1.yaml'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './summary/models/summary.v1.yaml'
      tags:
        - Summary
        - Internal
      deprecated: true

  '/v1/users/{userId}/summaries':
    parameters:
      - $ref: './common/parameters/tidepooluserid.yaml'
    post:
      operationId: GetUserSharedSummaries
      summary: Get User's Shared Summaries
      description: >-
        Retrieves summary information for all of the users who have granted access permission to the user specified by `userId`.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './summary/models/summaryrequest.v1.yaml'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './summary/models/summary.v1.yaml'
      tags:
        - Summary
        - Internal
      deprecated: true

  '/v1/clinics/{clinicId}/summaries':
    parameters:
      - $ref: './clinic/parameters/clinicid.v1.yaml'
    post:
      operationId: GetClinicPatientSummary
      summary: Get Clinic Patient Summary
      description: >-
        Returns summary information for all patients of a clinic.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './summary/models/summaryrequest.v1.yaml'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './summary/models/summary.v1.yaml'
      tags:
        - Summary
        - Internal
      deprecated: true

components:
  securitySchemes:
    sessionToken:
      $ref: './common/security/tidepoolsessiontoken.v1.yaml'
