name: publish

on:
  push:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        target: [ check_docs, check_specs ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup script environment
        run: |
            make install_check_tools check_check_tools
      - name: Check the documentation
        run: |
            make ${{ matrix.target }}

  publish:
    strategy:
      matrix:
        target: [ publish_public, publish_private ]
    needs: [ check ]
    runs-on: ubuntu-latest
    env:
      PUBLIC_STOPLIGHT_TOKEN: ${{ secrets.PUBLIC_STOPLIGHT_TOKEN }}
      PRIVATE_STOPLIGHT_TOKEN: ${{ secrets.PRIVATE_STOPLIGHT_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Setup script environment
        run: |
            make install_publish_tools check_publish_tools
      - name: Publish the documentation
        run: |
            make ${{ matrix.target }}
